"""
Run every test of an approved analysis plan (copied into the session's experiment folder).

Reads config.json next to this file, runs each test's block on the declared
dataset, and writes results/<test id>.json. A test that fails writes its error
instead of results, and the script exits with status 1 so the run is recorded
as failed. Nothing here is generated by a model.
"""

import json
import sys
import traceback
from pathlib import Path

import analysis_blocks as ab
from panel_data import PanelLayout, load_indicator


def main() -> int:
    here = Path(__file__).resolve().parent
    config = json.loads((here / "config.json").read_text(encoding="utf-8"))
    layout = PanelLayout.from_dict(config["layout"])
    cache = {}

    def load(indicator, split=None, attribute=None):
        key = (indicator, split, attribute)
        if key not in cache:
            cache[key] = load_indicator(layout, indicator, split, attribute)
        return cache[key].copy()

    out_dir = here / "results"
    out_dir.mkdir(exist_ok=True)
    failed = 0
    for test in config["tests"]:
        spec = ab.BLOCKS[test["block"]]
        record = {"test_id": test["id"], "block": test["block"], "params": test["params"]}
        try:
            record.update(spec.run(load, ab.with_defaults(spec, test["params"])))
            print(f"{test['id']} {test['block']}: {json.dumps(record['outputs'])}")
        except Exception as exc:  # recorded per test; the run still fails
            failed += 1
            record["error"] = f"{type(exc).__name__}: {exc}"
            record["traceback"] = traceback.format_exc()
            print(f"{test['id']} {test['block']}: FAILED {record['error']}", file=sys.stderr)
        (out_dir / f"{test['id']}.json").write_text(json.dumps(record, indent=2), encoding="utf-8")
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
